name: File Checker

on: ['push', 'pull_request']
    
jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: File check
        run: ls
